### ISSUE TITLE
celery stops with 'module' object has no attribute 'celeryconfig'

### ISSUE THREAD

**Issue by fvanderbiest** [kartoza/docker-geosafe#30]
```
~/workspace/docker-geosafe/deployment (develop *)$ make geosafe-celery-log
Attaching to geonodedocker_celery_1
celery_1                     | WARNINGS:
celery_1                     | base.ResourceBase.tkeywords: (fields.W340) null has no effect on ManyToManyField.
celery_1                     | Traceback (most recent call last):
celery_1                     |   File "/usr/local/bin/celery", line 11, in <module>
celery_1                     |     sys.exit(main())
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
celery_1                     |     main()
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
celery_1                     |     cmd.execute_from_commandline(argv)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
celery_1                     |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
celery_1                     |     return self.handle_argv(self.prog_name, argv[1:])
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
celery_1                     |     return self.execute(command, argv)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
celery_1                     |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
celery_1                     |     return self(*args, **options)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
celery_1                     |     ret = self.run(*args, **kwargs)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
celery_1                     |     state_db=self.node_format(state_db, hostname), **kwargs
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 100, in __init__
celery_1                     |     self.setup_instance(**self.prepare_args(**kwargs))
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 131, in setup_instance
celery_1                     |     signals.worker_init.send(sender=self)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
celery_1                     |     response = receiver(signal=self, sender=sender, **named)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 76, in on_worker_init
celery_1                     |     self.worker_fixup.install()
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 325, in __get__
celery_1                     |     value = obj.__dict__[self.__name__] = self.__get(obj)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 68, in worker_fixup
celery_1                     |     self._worker_fixup = DjangoWorkerFixup(self.app)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 101, in __init__
celery_1                     |     self.db_reuse_max = self.app.conf.get('CELERY_DB_REUSE_MAX', None)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 325, in __get__
celery_1                     |     value = obj.__dict__[self.__name__] = self.__get(obj)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 629, in conf
celery_1                     |     return self._get_config()
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 453, in _get_config
celery_1                     |     self.loader.config_from_object(self._config_source)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/loaders/base.py", line 140, in config_from_object
celery_1                     |     obj = self._smart_import(obj, imp=self.import_from_cwd)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/celery/loaders/base.py", line 161, in _smart_import
celery_1                     |     return symbol_by_name(path, imp=imp)
celery_1                     |   File "/usr/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 101, in symbol_by_name
celery_1                     |     return getattr(module, cls_name) if cls_name else module
celery_1                     | AttributeError: 'module' object has no attribute 'celeryconfig'
geonodedocker_celery_1 exited with code 1
```

**Comment by fvanderbiest** [comment]
No more an issue, I had a bad config in my compose override file.
Sorry for the noise.
